name: Update README2

on:
  schedule:
    - cron: '0 */12 * * *' # Cada 12 horas
  workflow_dispatch:

permissions:
    contents: write #necesario para hacer commits
    actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: jamesgeorge007/github-activity-readme@master

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
